[package]
name = "smoltcp"
version = "0.4.0"
authors = ["whitequark <whitequark@whitequark.org>"]
description = "A TCP/IP stack designed for bare-metal, real-time systems without a heap."
documentation = "https://docs.rs/smoltcp/"
homepage = "https://github.com/m-labs/smoltcp"
repository = "https://github.com/m-labs/smoltcp.git"
readme = "README.md"
keywords = ["ip", "tcp", "udp", "ethernet", "network"]
categories = ["embedded"]
license = "0BSD"

[dependencies]
byteorder = { version = "1.0", default-features = false }
managed = { version = "0.4.0", default-features = false }
log = { version = "0.3", default-features = false, optional = true }
libc = { version = "0.2.18", optional = true }

[dev-dependencies]
log = "0.3"
env_logger = "0.4"
getopts = "0.2"

[features]
std = ["managed/std"]
alloc = ["managed/alloc"]
verbose = []
"phy-raw_socket" = ["std", "libc"]
"phy-tap_interface" = ["std", "libc"]
"socket-raw" = []
"socket-udp" = []
"socket-tcp" = []
"protocol-igmp" = []
default = ["std", "log",
  "phy-raw_socket", "phy-tap_interface",
  "socket-raw", "socket-udp", "socket-tcp", "protocol-igmp"]

[[example]]
name = "tcpdump"

[[example]]
name = "server"

[[example]]
name = "client"

[[example]]
name = "ping"

[[example]]
name = "loopback"

[[example]]
name = "multicast"
